### ISSUE TITLE
Citation module: 'retrieving information' signal is needed

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bdutilities.app#16]
Some citation levels need a bit of time to generate information.
![image.png](https://images.zenhubusercontent.com/59e62044a468affe6df6fea1/0279f58c-9fa2-4db5-a53a-c9a23aca2b88)

We should have a user information message to signal that the information is being generated, like we have in the data download module: 
![image.png](https://images.zenhubusercontent.com/59e62044a468affe6df6fea1/c94b6beb-dcbc-4315-a478-e3db42e0b4e5)

**Comment by thiloshon** [comment]
Fixed
