### ISSUE TITLE
Choosing `EcoEngine` crashes the app

### ISSUE THREAD

**Issue by saxenism** [bd-R/bdutilities.app#28]
![image](https://user-images.githubusercontent.com/32522659/126186203-71d77c00-efde-4660-b2eb-7b610e934598.png)

When you select the EcoEngine option to download your dataset, the dashboard.experiment app deployed at https://rahulch.shinyapps.io/dashboard_experiment/ crashes.

**Comment by tom-gu** [comment]
@thiloshon 
We can (and should) remove EcoEngine from the list
![image](https://user-images.githubusercontent.com/16609623/137936766-ea50591b-76a0-4c99-b72f-446ebf20dd87.png)
