### ISSUE TITLE
Data upload/download module: map is not showing non-gbif records

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bdutilities.app#4]
In Data download/upload module:

Only records with decimalLongitude & decimalLatitude i.e. gbif records via rgbif) are shown in the maps. All the spocc downloads have a longitude; latitude (it's pre-Darwinization).

Also, in gbif data there're tree fields duplicates:

![image](https://user-images.githubusercontent.com/16609623/66909357-4985dd80-f015-11e9-9113-f70242f5da75.png)

**Comment by thiloshon** [comment]
Fixed with #7
