### ISSUE TITLE
Uploading a DwC-A zip file is not working

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bdutilities.app#8]
Checked in our Binder env
![image](https://user-images.githubusercontent.com/16609623/69140608-7a9d7600-0acb-11ea-94c5-f2681f5bd73f.png)

It used to work :confused:

**Comment by thiloshon** [comment]
I am not able to reproduce this in binder or local. @tom-gu can you please share the DWCA file that is throwing this error?

I am using the following file 
[0001315-180824113759888 New .zip](https://github.com/bd-R/bdutilities.app/files/3963810/0001315-180824113759888.New.zip)

**Comment by tom-gu** [comment]
Working!
